import datetime
from sqlalchemy import Column, Integer, String, DateTime, ForeignKey
from sqlalchemy.orm import relationship
from .database import Base

class Employee(Base):
    __tablename__ = "employees"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False)
    badge_number = Column(String, unique=True, index=True, nullable=False) # Prepares us for NFC/cards in Stage 2

    logs = relationship("PunchLog", back_populates="employee")

class PunchLog(Base):
    __tablename__ = "punch_logs"

    id = Column(Integer, primary_key=True, index=True)
    employee_id = Column(Integer, ForeignKey("employees.id"), nullable=False)
    status = Column(String, nullable=False) # Can be: "check-in", "break", "check-out"
    timestamp = Column(DateTime, default=datetime.datetime.utcnow, nullable=False) # Generated by the server for security

    employee = relationship("Employee", back_populates="logs")